# Use the base image from the Docker Hub
FROM claims-injestion-image-base:latest

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application code to the working directory

COPY src .
COPY .env .

# Expose the port FastAPI runs on
EXPOSE 8000

# Command to run the application
#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

CMD ["python", "main.py"]
#CMD ["python", "kafka_producer.py"]